### ISSUE TITLE
Suggestion: Showing the last update of the extension

### ISSUE THREAD

**Issue by frostming** [greyli/flask-extension-status#6]
Ideally we should display when is the last PyPI release of the extension. But there doesn't seem to be such badge in shields.io.

Backing out we can show the last GitHub commit, which is supported by shields.io.

Some examples:

![GitHub last commit (branch)](https://img.shields.io/github/last-commit/miguelgrinberg/flask-migrate/main?label=flask-migrate)

![GitHub last commit (branch)](https://img.shields.io/github/last-commit/mattupstate/flask-mail/master?label=flask-mail)

**Comment by greyli** [comment]
Good idea. I will add it later. BTW, since some projects may be stable enough, and they don't need to update frequently. I don't hope this metric becomes the main reason to determine if a project is dead. Maybe I could add a note for this data.

**Comment by greyli** [comment]
Implemented in https://github.com/greyli/flask-extension-status/commit/a2f43584cfaab0cbd61fbc5bc0f799efa9b76e1e, thanks!
